# Generated by Django 3.1.5 on 2021-01-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Cost_per_minute', models.IntegerField()),
                ('Cost_per_minute_from_8pm_to_2am', models.IntegerField()),
                ('Cost_per_minute_from_2am_to_6am', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=60)),
                ('Shift_number', models.IntegerField()),
                ('Computer_IP', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=60)),
                ('Organization_address', models.CharField(max_length=60)),
                ('Organization_phone_number', models.CharField(max_length=20)),
                ('Date_of_start_of_session', models.DateTimeField()),
                ('Date_of_end_of_session', models.DateTimeField()),
                ('Number_of_minutes_of_session', models.IntegerField()),
                ('Total_cost', models.IntegerField()),
                ('Cost_per_minute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.price')),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.user')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=60)),
                ('Organization_address', models.CharField(max_length=60)),
                ('Organization_phone_number', models.CharField(max_length=20)),
                ('Number_of_minutes_of_session', models.IntegerField()),
                ('Total_cost', models.IntegerField()),
                ('Cost_per_minute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.price')),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.user')),
            ],
        ),
    ]
