# Generated by Django 3.1.5 on 2021-01-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=30)),
                ('Date_of_start_of_session', models.CharField(max_length=30)),
                ('Date_of_end_of_session', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=60)),
                ('Organization_address', models.CharField(max_length=60)),
                ('Organization_phone_number', models.CharField(max_length=20)),
                ('Operator_Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.operator')),
                ('Price_Cost_per_minute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.price')),
            ],
        ),
        migrations.RemoveField(
            model_name='bird',
            name='animal_id',
        ),
        migrations.RemoveField(
            model_name='reptile',
            name='animal_id',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Bird',
        ),
        migrations.DeleteModel(
            name='Feeding_ration',
        ),
        migrations.DeleteModel(
            name='Habitat_area',
        ),
        migrations.DeleteModel(
            name='Reptile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='client',
            name='Operator_Employee_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.operator'),
        ),
        migrations.AddField(
            model_name='client',
            name='Price_Cost_per_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.price'),
        ),
        migrations.AddField(
            model_name='client',
            name='Receipt_shift_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.receipt'),
        ),
    ]
